name: fannelance
description: "User Mobile App."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.11
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.0.0
  flutter_stripe: ^10.0.0
  fluttericon: ^2.0.0
  font_awesome_flutter: ^10.7.0
  iconsax: ^0.0.8
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  jwt_decoder: ^2.0.1
  pinput: ^4.0.0
  searchfield: ^0.9.2
  url_launcher: ^6.2.6
  geolocator: ^12.0.0
  input_history_text_field: ^0.2.0
  flutter_svg:
  geocoding: ^3.0.0
  

dev_dependencies:
  flutter_lints: ^2.0.0 
  flutter_test:
    sdk: flutter
  

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/
    - .env
    
  fonts:
    - family: Gilroy-SemiBold
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf

    - family: Gilroy-Bold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf

    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf



flutter_native_splash:
  
  color: "#42a5f5"
  image:  assets/icons/logo.png
  android_gravity : center
  android_12:
    image: assets/icons/logo.png
    android_gravity: fill
    

    color: "#1498B7"

