name: fannelance
description: "User Mobile App."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  audioplayers: ^6.0.0
  circular_countdown_timer: ^0.2.3
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.11
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.0.0
  flutter_stripe: ^10.0.0
  flutter_svg: null
  fluttericon: ^2.0.0
  font_awesome_flutter: ^10.7.0
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  iconsax: ^0.0.8
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  jwt_decode: ^0.3.1
  jwt_decoder: ^2.0.1
  pinput: ^4.0.0
  provider: ^6.1.2
  searchfield: ^0.9.2
  socket_io_client: ^2.0.3+1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logos/
    - assets/sounds/
    - assets/
    - .env

  fonts:
    - family: Gilroy-SemiBold
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf

    - family: Gilroy-Bold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf

    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

flutter_native_splash:
  color: "#1498B7"
  image: assets/icons/logo.png
  android_gravity: center
  icon_background_color: "#1498B7"

  android_12:
    image: assets/icons/logo.png
    android_gravity: center 
    color: "#1498B7"
    icon_background_color: "#1498B7"
