name: fannelance
description: "User Mobile App."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_rating_bar: ^4.0.1
  flutter_stripe: ^10.0.0
  fluttericon: ^2.0.0
  iconsax: ^0.0.8
  searchfield: ^0.9.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/
    - .env

  fonts:
    - family: Gilroy-SemiBold
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf

    - family: Gilroy-Bold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf

    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
